#!/usr/bin/sh

file=$1
loc=$(dirname $file)
if [[ $* == *--dir* ]]; then 
    loc=$loc/pdfs/
    mkdir -p $loc
    out=$loc/$(basename "$file" .md).pdf
else
    out=$loc/pdf$(basename "$file" .md).pdf
fi

pandoc \
    --pdf-engine=xelatex \
    -o "$out" \
    "$file" &
