#!/usr/bin/sh
mntable=$(lsblk -lp | grep "disk $\|part $" | awk '{print $1 " (" $4 ")"}')
chosen=$(echo "$mntable" | rofi -dmenu -p "Device location" | awk '{print $1}')
[[ $chosen == "" ]] && exit 1
dest=$(find /media /mnt -type d | rofi -dmenu -p "Destination")
[[ $dest == "" ]] && exit 1
if [[ ! -d $dest ]]; then 
    cnew=$(rofi -dmenu -p "create new?")
    [[ $cnew = "yes" || $cnew = "y" ]] && sudo mkdir -p $dest
fi
sudo mount $chosen $dest
notify-send "Mounted" "$chosen -> $dest"
