#!/usr/bin/sh
mntable=$(lsblk -lp | grep "disk $\|part $" | awk '{print $1 " (" $4 ")"}')
choice=$(echo "$mntable" | rofi -dmenu -p "Device location" | awk '{print $1}')
[[ $choice == "" ]] && exit 1
dest=$(find /media /mnt -type d | rofi -dmenu -p "Destination")
[[ $dest == "" ]] && exit 1

password=$(rofi -dmenu -p "sudo password: ")
[[ $password == "" ]] && exit 1

if [[ ! -d $dest ]]; then 
    cnew=$(rofi -dmenu -p "create new?")
    [[ $cnew = "yes" || $cnew = "y" ]] && echo $password | sudo -S mkdir -p $dest
fi
echo $password | sudo -S mount $choice $dest
notify-send "Mounted" "$choice -> $dest"
