#!/usr/bin/sh
[[ $1 == "istanbul" ]] && sudo timedatectl set-timezone Europe/Istanbul && exit
[[ $1 == "warsaw" ]] && sudo timedatectl set-timezone Europe/Warsaw && exit
[[ $1 == "stockholm" ]] && sudo timedatectl set-timezone Europe/Stockholm && exit
