#!/bin/zsh

export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="firefox"

export XDG_CONFIG_HOME="$HOME/.config"
export JAVA_HOME=/usr/bin/java

export PATH=$PATH:$XDG_CONFIG_HOME/scripts
export PATH=$PATH:$JAVA_HOME
export PATH=$PATH:~/.local/share/gem/ruby/3.0.0/bin/

export CM_SELECTIONS="clipboard"
export CM_DEBUG=0
export CM_HISTLENGTH=10
export CM_MAX_CLIPS=1000
export CM_LAUNCHER="rofi"
