source ~/.config/shell/profile


export ZSH="/home/adam/.oh-my-zsh"

ZSH_THEME="jnrowe"

DISABLE_CORRECTION="true"

plugins=(git)

set -o vi

source $ZSH/oh-my-zsh.sh

source ~/.config/shell/completion.zsh
source ~/.config/shell/key-bindings.zsh
